[package]
name = "air-script"
version = "0.5.0"
description = "AirScript language compiler"
authors.workspace = true
readme = "README.md"
license.workspace = true
repository.workspace = true
documentation = "https://0xpolygonmiden.github.io/air-script/"
categories = ["compilers", "cryptography"]
keywords = ["air", "stark", "zero-knowledge", "zkp"]
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "airc"
path = "src/main.rs"

[dependencies]
air-codegen-winter = { package = "air-codegen-winter", path = "../codegen/winterfell", version = "0.5" }
air-codegen-plonky3 = { package = "air-codegen-plonky3", path = "../codegen/plonky3", version = "0.5" }
air-ir = { package = "air-ir", path = "../air", version = "0.5" }
air-parser = { package = "air-parser", path = "../parser", version = "0.5" }
air-pass = { package = "air-pass", path = "../pass", version = "0.5" }
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11"
log = { version = "0.4", default-features = false }
miden-diagnostics = { workspace = true }
mir = { package = "air-mir", path = "../mir", version = "0.5" }

[dev-dependencies]
expect-test = "1.4"

# 0xMiden Plonky3 Fork. TODO: switch back to it when the PR is merged. 
#p3-air = { package = "p3-air", git="https://github.com/0xMiden/Plonky3", rev = "2e6ff23090b5bd5138695ceb757181443a523c6d", default-features = false }
#p3-challenger = { package = "p3-challenger", git="https://github.com/0xMiden/Plonky3", rev = "2e6ff23090b5bd5138695ceb757181443a523c6d", default-features = false }
#p3-circle = { package = "p3-circle", git="https://github.com/0xMiden/Plonky3", rev = "2e6ff23090b5bd5138695ceb757181443a523c6d", default-features = false }
#p3-commit = { package = "p3-commit", git="https://github.com/0xMiden/Plonky3", rev = "2e6ff23090b5bd5138695ceb757181443a523c6d", default-features = false }
#p3-field = { package = "p3-field", git="https://github.com/0xMiden/Plonky3", rev = "2e6ff23090b5bd5138695ceb757181443a523c6d", default-features = false }
#p3-fri = { package = "p3-fri", git="https://github.com/0xMiden/Plonky3", rev = "2e6ff23090b5bd5138695ceb757181443a523c6d", default-features = false }
#p3-matrix = { package = "p3-matrix", git="https://github.com/0xMiden/Plonky3", rev = "2e6ff23090b5bd5138695ceb757181443a523c6d", default-features = false }
#p3-merkle-tree = { package = "p3-merkle-tree", git="https://github.com/0xMiden/Plonky3", rev = "2e6ff23090b5bd5138695ceb757181443a523c6d", default-features = false }
#p3-goldilocks = { package = "p3-goldilocks", git="https://github.com/0xMiden/Plonky3", rev = "2e6ff23090b5bd5138695ceb757181443a523c6d", default-features = false }
#p3-sha256 = { package = "p3-sha256", git="https://github.com/0xMiden/Plonky3", rev = "2e6ff23090b5bd5138695ceb757181443a523c6d", default-features = false }
#p3-symmetric = { package = "p3-symmetric", git="https://github.com/0xMiden/Plonky3", rev = "2e6ff23090b5bd5138695ceb757181443a523c6d", default-features = false }
#p3-uni-stark = { package = "p3-uni-stark", git="https://github.com/0xMiden/Plonky3", rev = "2e6ff23090b5bd5138695ceb757181443a523c6d", default-features = false }

# MassaLabs fork
p3-air = { package = "p3-air", git="https://github.com/massalabs/Plonky3", rev = "064a1a5d2c5701ecf1dc38602c307beb50ed2baa", default-features = false }
p3-challenger = { package = "p3-challenger", git="https://github.com/massalabs/Plonky3", rev = "064a1a5d2c5701ecf1dc38602c307beb50ed2baa", default-features = false }
p3-circle = { package = "p3-circle", git="https://github.com/massalabs/Plonky3", rev = "064a1a5d2c5701ecf1dc38602c307beb50ed2baa", default-features = false }
p3-commit = { package = "p3-commit", git="https://github.com/massalabs/Plonky3", rev = "064a1a5d2c5701ecf1dc38602c307beb50ed2baa", default-features = false }
p3-field = { package = "p3-field", git="https://github.com/massalabs/Plonky3", rev = "064a1a5d2c5701ecf1dc38602c307beb50ed2baa", default-features = false }
p3-fri = { package = "p3-fri", git="https://github.com/massalabs/Plonky3", rev = "064a1a5d2c5701ecf1dc38602c307beb50ed2baa", default-features = false }
p3-matrix = { package = "p3-matrix", git="https://github.com/massalabs/Plonky3", rev = "064a1a5d2c5701ecf1dc38602c307beb50ed2baa", default-features = false }
p3-merkle-tree = { package = "p3-merkle-tree", git="https://github.com/massalabs/Plonky3", rev = "064a1a5d2c5701ecf1dc38602c307beb50ed2baa", default-features = false }
p3-miden-air = { package = "miden-air", git="https://github.com/massalabs/Plonky3", rev = "064a1a5d2c5701ecf1dc38602c307beb50ed2baa", default-features = false }
p3-goldilocks = { package = "p3-goldilocks", git="https://github.com/massalabs/Plonky3", rev = "064a1a5d2c5701ecf1dc38602c307beb50ed2baa", default-features = false }
p3-sha256 = { package = "p3-sha256", git="https://github.com/massalabs/Plonky3", rev = "064a1a5d2c5701ecf1dc38602c307beb50ed2baa", default-features = false }
p3-symmetric = { package = "p3-symmetric", git="https://github.com/massalabs/Plonky3", rev = "064a1a5d2c5701ecf1dc38602c307beb50ed2baa", default-features = false }
p3-uni-stark = { package = "p3-uni-stark", git="https://github.com/massalabs/Plonky3", rev = "064a1a5d2c5701ecf1dc38602c307beb50ed2baa", default-features = false }

winter-air = { package = "winter-air", version = "0.12", default-features = false }
winter-math = { package = "winter-math", version = "0.12", default-features = false }
winter-utils = { package = "winter-utils", version = "0.12", default-features = false }
winter-prover = { package = "winter-prover", version = "0.12", default-features = false }
winter-verifier = { package = "winter-verifier", version = "0.12", default-features = false }
winterfell = { package = "winterfell", version = "0.12", default-features = false }
