# Runs build related jobs.

name: build

# Limits workflow concurrency to only the latest commit in the PR.
concurrency:
    group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
    cancel-in-progress: true

on:
    push:
        branches: [main, next]
    pull_request:
        types: [opened, reopened, synchronize]

permissions:
    contents: read

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: Swatinem/rust-cache@v2
        with:
          # Only update the cache on push onto the next branch. This strikes a nice balance between
          # cache hits and cache evictions (github has a 10GB cache limit).
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/next' }}
      - name: Install rust
        run: rustup update --no-self-update 
      - name: Run check
        run: make check
