name: lint

# Limits workflow concurrency to only the latest commit in the PR.
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  clippy:
    name: Clippy
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy
      - name: Install nightly rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt
      - name: Run clippy
        run: make lint

  rustfmt:
    name: rustfmt
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt
      - name: Run rustfmt
        run: make format-check

  doc:
    name: doc
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Build docs
        run: make doc
